[toolchain]
channel = "nightly-2023-10-21"
components = [
    "rust-src",     # Required for Rust-analyzer
    "llvm-tools",   # Required for working with rustc internals
    "rustc-dev"     # Contains compiler src
    ]