[package]
name = "test_package"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Martens"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc_middle = "0.0.0"
rustc_hir  = "0.0.0"
rustc_driver = "0.0.0"
rustc_interface  = "0.0.0"
rustc_error_codes = "0.0.0"
rustc_errors = "0.0.0"
rustc_session = "0.0.0"
rustc_span = "0.0.0"
rustc_ast_pretty = "0.0.0"
rustc-hash = "1.0.1"

[[example]]
name = "playground"

[[example]]
name = "query_rustc_interface"

[[example]]
name = "query_rustc_driver"