[package]
name = "test_package"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Martens"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc_middle    = { path = "../rust/compiler/rustc_middle" }
rustc_hir       = { path = "../rust/compiler/rustc_hir" }
rustc_driver    = { path = "../rust/compiler/rustc_driver" }
rustc_interface = { path = "../rust/compiler/rustc_interface" }

