[package]
name = "compiler"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Martens"]


[package.metadata.rust-analyzer]
rustc_private=true


[[example]]
name = "query_rustc_interface"

[[example]]
name = "query_rustc_driver"