[package]
name = "mayday"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Martens"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }

[package.metadata.rust-analyzer]
rustc_private=true